### ISSUE TITLE
background genome fasta file

### ISSUE THREAD

**Issue by alex-berry** [eclarke/swga#18] opened 2015-03-11 18:38 UTC
Is there a maximum file size for background genomes? My genome fasta file is 7.6GB. It reads the foreground easily, but I get the following error when inputting my background genome file:

Enter path to background genome file, in FASTA format: /mnt/1tb/thesis_data/SWGA/infestans_genome.fasta

Error reading /mnt/1tb/thesis_data/SWGA/infestans_genome.fasta: invalid FASTA format?
Traceback (most recent call last):
  File "/home/alex/swga_workspace_2015.03.11/bin/swga", line 9, in <module>
    load_entry_point('swga==0.3.2', 'console_scripts', 'swga')()
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/swga/commands/swga_entry.py", line 47, in main
    command_opts[args.command](remaining, args.config)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/swga/commands/init.py", line 71, in main
    bg_length, bg_nrecords = fasta_stats(bg_genome_fp)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/swga/commands/init.py", line 118, in fasta_stats
    fasta = Fasta(fasta_fp)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/pyfaidx/__init__.py", line 540, in __init__
    filt_function=filt_function)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/pyfaidx/__init__.py", line 216, in __init__
    self.read_fai(split_char)
  File "/home/alex/swga_workspace_2015.03.11/local/lib/python2.7/site-packages/pyfaidx/__init__.py", line 244, in read_fai
    raise ValueError('Duplicate key "%s"' % rname)
ValueError: Duplicate key "['M00281:39:000000000-AAGY4:1:1101:15888:1332']"

**Comment by sesh-sas** [comment] 2015-03-11 18:48
ValueError: Duplicate key "['M00281:39:000000000-AAGY4:1:1101:15888:1332']"

Indicates that there are two sequences in your fasta file with the same name, so the quick fix would be ensuring that that doesn't happen.  I see that you're using short read data, are your forward and reverse reads names the same?

**Comment by alex-berry** [comment] 2015-03-11 18:57
It's certainly possible that they have the same names. I just haven't had this problem with this file previously. I'll go back to the original sequencing files and rename the reverse reads before concatenating. Thanks, Sesh.

**Comment by sesh-sas** [comment] 2015-03-11 19:01
Also grepping for M00281:39:000000000-AAGY4:1:1101:15888:1332 in the current genome file.

We haven't tested the code on illumina reads converted to fasta yet, so we haven't had a chance to see if anything specific about the way illumina names things causes problems.
Also, obviously, we have no idea how mer counting in the background genome will go with the short read data.

**Comment by eclarke** [comment] 2015-03-11 19:03
Also when you say "previously" what version of SWGA are you referring to? I.e. when it was still dependent on dna-utils?

Erik

**Comment by sesh-sas** [comment] 2015-03-11 19:06
It appears that the issue is that illumina names the reads as follows:
FWD: @M00281:52:000000000-G0212:1:1101:16138:1346 1:N:0:1
REV: @M00281:52:000000000-G0212:1:1101:16138:1346 2:N:0:1

The fasta parser truncates the names at the first blank space, so these reads would then be named the same.  So replacing the blank spaces in the name with an underscore should also fix this.

**Comment by alex-berry** [comment] 2015-03-11 19:20
Correct. The original SelectiveWholeGenomeAmplificationUI was able to read this particular fasta file. I can replace spaces with underscores and see what happens.

**Comment by alex-berry** [comment] 2015-03-11 22:33
After translating spaces to underscores in the background genome file I tried again. It seemed to read it this time but quit the program before finishing reading the file. I received the message "Killed" once and "Segmentation Fault" the next two times.

Enter path to foreground genome file, in FASTA format: /mnt/1tb/thesis_data/SWGA/cruzi_genome.fasta

Foreground genome: /mnt/1tb/thesis_data/SWGA/cruzi_genome.fasta
  Length:  38589511 bp
  Records: 27019

Enter path to background genome file, in FASTA format: /mnt/1tb/thesis_data/SWGA/infestans_genome2.fasta
Killed
(swga_workspace)alex@alex-MS-7821 /mnt/1tb/thesis_data/SWGA/New_SWGA_2015.03.11/swga_workspace/swga-master/new_swga_2015.03.11 $ swga init

Enter path to background genome file, in FASTA format: /mnt/1tb/thesis_data/SWGA/infestans_genome2.fasta
Segmentation fault
(swga_workspace)alex@alex-MS-7821 /mnt/1tb/thesis_data/SWGA/New_SWGA_2015.03.11/swga_workspace/swga-master/new_swga_2015.03.11 $

**Comment by sesh-sas** [comment] 2015-03-11 23:03
Now that means the file is too big.  What kind of computer are you working on?

**Comment by alex-berry** [comment] 2015-03-12 00:20
I don't think the PC is the issue here. It is a very large file for a genome but it's because it's Illumina reads. I'm running Linux Mint with 24 GB RAM. The dna-utils stuff can handle this file so I'm using that for now.

**Comment by sesh-sas** [comment] 2015-03-12 00:29
Can you give us access to the file so we can try some stuff with it?

**Comment by alex-berry** [comment] 2015-03-12 02:01
Sure. The zipped file is 1.4GB. How do you want it?

**Comment by sesh-sas** [comment] 2015-03-12 12:30
This parses on a centos 6 server.  So it appears the error is system or OS dependent.  What is your stack size limit?

**Comment by alex-berry** [comment] 2015-03-12 15:57
8192 kb

**Comment by alex-berry** [comment] 2015-03-12 16:00
8MB is the default for most linux machines as I understand.

**Comment by sesh-sas** [comment] 2015-03-12 16:09
Again it's os dependent.  Try increasing it to 20000

'ulimit -s 20000'

**Comment by eclarke** [comment] 2015-03-12 17:24
Hi Alex,

I've pushed a fix to the code (c855b82ad716203450a9f07a435f80d25d1f8d6f) that uses a different method of getting the background genome length and should work with your Illumina reads. You don't need to alter the record names anymore either. Please follow the update instructions [here](https://github.com/eclarke/swga/wiki/Quick-Start) and let me know if there are any other problems.

It's worth pointing out that we do not support using short read data for the foreground genome, since we use location-based statistics that wouldn't be meaningful with short reads. It should work with assembled contigs though. I don't know if that's relevant to your project or not.

Thanks for working with us on this,
Erik

**Closed by eclarke** 2015-03-12 17:24 UTC

**Comment by alex-berry** [comment] 2015-03-12 17:49
That worked great! Thanks!

I do have another stupid question, though: "Enter path to exclusionary sequence(s), in FASTA format"
I'm assuming it can handle multiple exclusion files, but neither space- or comma-separated seem to work. For example: /mnt/1tb/thesis_data/SWGA/cruzi_maxicircle.fasta /mnt/1tb/thesis_data/SWGA/cruzi_minicircle.fasta /mnt/1tb/thesis_data/SWGA/Ti_mitogen.fasta 
Thanks for all your help!

**Comment by eclarke** [comment] 2015-03-12 17:56
Glad it worked! And right now it doesn't handle multiple exclusionary files, but you can concatenate them into one file and pass that in, e.g. 

`cat cruzi_maxicircle.fasta cruzi_minicircle.fasta Ti_mitogen.fasta > excluded_seqs.fasta`

**Comment by alex-berry** [comment] 2015-03-12 19:34
That's what I ended up doing. It's a really quick workaround. I just wanted to bring it to your attention in case it was an easy-to-fix bug. It's still running but everything seems to be working smoothly. I'll start a new post if I run into anything else. Thanks!
